apiVersion: batch/v1
kind: Job
metadata:
  name: job
spec:
  template:
    spec:
      schedulerName: sniffer
      containers:
      - name: job
        image: busybox
        command: [echo, potato]
      restartPolicy: Never
  backoffLimit: 4
