// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.3
// source: api/sniffer.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// SnifferServiceClient is the client API for SnifferService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnifferServiceClient interface {
	Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error)
}

type snifferServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnifferServiceClient(cc grpc.ClientConnInterface) SnifferServiceClient {
	return &snifferServiceClient{cc}
}

func (c *snifferServiceClient) Send(ctx context.Context, in *SendRequest, opts ...grpc.CallOption) (*SendResponse, error) {
	out := new(SendResponse)
	err := c.cc.Invoke(ctx, "/api.SnifferService/Send", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnifferServiceServer is the server API for SnifferService service.
// All implementations must embed UnimplementedSnifferServiceServer
// for forward compatibility
type SnifferServiceServer interface {
	Send(context.Context, *SendRequest) (*SendResponse, error)
	mustEmbedUnimplementedSnifferServiceServer()
}

// UnimplementedSnifferServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSnifferServiceServer struct {
}

func (UnimplementedSnifferServiceServer) Send(context.Context, *SendRequest) (*SendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Send not implemented")
}
func (UnimplementedSnifferServiceServer) mustEmbedUnimplementedSnifferServiceServer() {}

// UnsafeSnifferServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnifferServiceServer will
// result in compilation errors.
type UnsafeSnifferServiceServer interface {
	mustEmbedUnimplementedSnifferServiceServer()
}

func RegisterSnifferServiceServer(s grpc.ServiceRegistrar, srv SnifferServiceServer) {
	s.RegisterService(&SnifferService_ServiceDesc, srv)
}

func _SnifferService_Send_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnifferServiceServer).Send(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.SnifferService/Send",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnifferServiceServer).Send(ctx, req.(*SendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnifferService_ServiceDesc is the grpc.ServiceDesc for SnifferService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnifferService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.SnifferService",
	HandlerType: (*SnifferServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Send",
			Handler:    _SnifferService_Send_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/sniffer.proto",
}
